name: 'hr_data_governance'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

packages:
  - package: elementary-data/dbt-data-reliability
    version: "*"

models:
  hr_data_governance:
    +materialized: table